# Generated by Django 3.0.1 on 2020-01-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Saarthi_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at']},
        ),
    ]
